# See syntax at: https://github.com/crate-ci/typos/blob/master/docs/reference.md

files.extend-exclude = [
]

[default.extend-ignore-identifiers]

default.extend-ignore-identifiers-re = [
]

# Respect ignore files.
files.ignore-files = true

default.extend-exclude = [
]

default.extend-ignore-re = [
]

[default.extend-words]
